#!/usr/bin/env python3
"""Splice HOS02 curated handout (HOS01-style) into 02-git-repositories-refactoring-hos-workflow.html."""
from __future__ import annotations

import pathlib
import re

from hos_verbatim_pdf_append import full_pdf_text_append, inject_verbatim_styles

BASE = pathlib.Path(__file__).resolve().parent
TARGET = BASE / "02-git-repositories-refactoring-hos-workflow.html"


def fig(src: str, cap: str) -> str:
    return (
        f'    <div class="hos-pdf-fig-wrap">\n'
        f'      <img class="hos-pdf-fig" src="hos02-pdf-figures/{src}" alt="{cap}" loading="lazy" decoding="async" />\n'
        f'      <div class="hos-pdf-fig-cap">{cap}</div>\n'
        f"    </div>\n"
    )


def build_handout() -> str:
    return "".join(
        [
            '  <!-- Complete HOS02A handout (content from PDF; curated like HOS01) -->\n',
            '  <section class="hos-pdf-source" aria-label="HOS02A full handout">\n',
            '    <div class="hos-kicker">HOS02A &mdash; complete handout</div>\n',
            '    <div class="hos-pdf-meta">\n',
            "      <strong>CS445 Software Process Management</strong><br />\n",
            "      HOS02A &mdash; Git Repositories and Refactoring<br />\n",
            "      Developed by Kina Anh Bui (04/10/2025) &middot; Reviewed by Sam Chung (04/11/2025) &middot; Reviewed by Clark Ngo (12/4/2025)\n",
            "    </div>\n\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p01_fig0.png", "PDF page 1 &mdash; course header (graphic)"),
            fig("p01_fig1.png", "PDF page 1 &mdash; module title block"),
            "    </div>\n\n",
            "    <h2>Before You Start</h2>\n",
            "    <ul>\n",
            "      <li>Screenshots may be different from your environment.</li>\n",
            "      <li>The directory path shown in screenshots may be different from yours.</li>\n",
            "      <li>The steps might have subtle discrepancies. Please use your best judgment while completing each step in this cookbook-style tutorial.</li>\n",
            "      <li>Some steps may not be explained in detail. If you are not sure what to do:\n",
            "        <ol>\n",
            "          <li>Consult the resources from the course.</li>\n",
            "          <li>If you cannot solve the problem after a few tries (usually 15&ndash;30 minutes), ask a TA for help.</li>\n",
            "        </ol>\n",
            "      </li>\n",
            "    </ul>\n\n",
            "    <h2>Readings and Examples</h2>\n",
            "    <ul>\n",
            "      <li>Visit the CS 445 Repository for Examples.\n",
            '        <ol class="hos-subol">\n',
            "          <li>Select the related module.</li>\n",
            "          <li>Visit the README.md file.</li>\n",
            "          <li>Find examples for your practices.</li>\n",
            "        </ol>\n",
            "      </li>\n",
            "    </ul>\n\n",
            "    <h2>Learning Outcomes</h2>\n",
            "    <ul>\n",
            "      <li>Section 1: Accessing GitHub Codespaces</li>\n",
            "      <li>Section 2: Git Development Cycle</li>\n",
            "      <li>Section 3: Coding Tools in GitHub Codespaces</li>\n",
            "      <li>Section 4: Pushing Your Work to GitHub</li>\n",
            "    </ul>\n\n",
            "    <h2>Upload the following to your GitHub Repository generated from GitHub Classroom</h2>\n",
            "    <ol>\n",
            '      <li>Upload the screenshot of your &lsquo;01 New Branch&rsquo; as <span class="hos-cmd">01_new_branch_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;02 Listing Branches&rsquo; as <span class="hos-cmd">02_listing_branches_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;03 Git Status&rsquo; as <span class="hos-cmd">03_git_status_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;04 Git Add&rsquo; as <span class="hos-cmd">04_git_add_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;05 Git Commit&rsquo; as <span class="hos-cmd">05_git_commit_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;06 Pushing to GitHub&rsquo; as <span class="hos-cmd">06_pushing_github_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;07 Pulling Changes&rsquo; as <span class="hos-cmd">07_pulling_changes_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;08 Git Enable&rsquo; as <span class="hos-cmd">08_git_enable_firstname_lastname.png</span> by using your first and last name.</li>\n',
            '      <li>Upload the screenshot of your &lsquo;09 Linting Problems&rsquo; as <span class="hos-cmd">09_linting_problems_firstname_lastname.png</span> by using your first and last name.</li>\n',
            "    </ol>\n\n",
            "    <h2>Key Concepts</h2>\n\n",
            "    <h3>GitHub Codespaces</h3>\n",
            "    <ul>\n",
            "      <li><strong>Cloud-Based IDE:</strong> GitHub Codespaces is an online development environment that runs in the browser or via VS Code. It eliminates the need to install tools locally.</li>\n",
            "      <li><strong>Built-in Terminal:</strong> Comes pre-configured with Git, Python, and other common tools.</li>\n",
            "      <li><strong>Git Integration:</strong> Fully integrates with GitHub repositories for cloning, branching, committing, pushing, and creating pull requests directly inside Codespaces.</li>\n",
            "      <li><strong>No Cloning Needed:</strong> When you open a Codespace, you are already inside the project repository.</li>\n",
            "    </ul>\n\n",
            "    <h3>Git Development Cycle (in Codespaces)</h3>\n",
            "    <ul>\n",
            '      <li><strong>Branching:</strong> Use <span class="hos-cmd">git checkout -b branch_name</span> to create and switch to a new branch. Recommended for isolating features or fixes.</li>\n',
            "      <li><strong>Status Check:</strong> Use <span class=\"hos-cmd\">git status</span> to view untracked or modified files.</li>\n",
            "      <li><strong>Staging Files:</strong> Use <span class=\"hos-cmd\">git add --all</span> to stage all changes.</li>\n",
            '      <li><strong>Committing Changes:</strong> Use <span class="hos-cmd">git commit -m "message"</span> to save changes in local history.</li>\n',
            "      <li><strong>Pushing:</strong> Use <span class=\"hos-cmd\">git push origin branch_name</span> to sync your local branch with GitHub.</li>\n",
            "      <li><strong>Pull Request (PR):</strong> Created from the GitHub web interface to propose merging feature branches into <code>main</code>.</li>\n",
            "      <li><strong>Pulling Changes:</strong> Use <span class=\"hos-cmd\">git pull</span> to update your local repository with changes from the remote.</li>\n",
            "    </ul>\n\n",
            "    <h3>Debugging in Codespaces</h3>\n",
            "    <ul>\n",
            "      <li><strong>Breakpoints:</strong> Add a red dot to pause execution at a specific line.</li>\n",
            "      <li><strong>Start Debugging:</strong> Use <strong>Run &rarr; Start Debugging</strong> to begin.</li>\n",
            "      <li><strong>F11 (Step Into):</strong> Enters inside a function call.</li>\n",
            "      <li><strong>F10 (Step Over):</strong> Executes the current line and moves to the next one.</li>\n",
            "      <li><strong>Interactive Console:</strong> View variable values and output during step-by-step execution.</li>\n",
            "    </ul>\n\n",
            "    <h3>Error Analysis</h3>\n",
            "    <ul>\n",
            "      <li><strong>Syntax Errors:</strong> Typos, missing colons, incorrect indentation, or invalid syntax.</li>\n",
            "      <li><strong>Problems Tab:</strong> Displays errors when files are saved with invalid Python syntax.</li>\n",
            "    </ul>\n\n",
            "    <h3>Linting</h3>\n",
            "    <ul>\n",
            "      <li><strong>Pylint Setup:</strong> Install the Pylint extension from the VS Code Marketplace.</li>\n",
            "      <li><strong>Automatic Detection:</strong> Saving a <span class=\"hos-cmd\">.py</span> file shows style and logic warnings.</li>\n",
            "      <li><strong>Problems Tab:</strong> Linting warnings appear alongside syntax errors.</li>\n",
            "    </ul>\n\n",
            "    <h3>Git Tools in Codespaces</h3>\n",
            "    <ul>\n",
            "      <li><strong>Source Control Tab:</strong> View, commit, and push changes visually.</li>\n",
            '      <li><strong>Settings:</strong> Ensure <strong>Git: Enabled</strong> is turned on.</li>\n',
            "    </ul>\n\n",
            "    <h2>Section 1: Accessing GitHub Codespaces</h2>\n",
            "    <p>Follow the instructions here.</p>\n",
            "    <p>GitHub Codespaces are online cloud-based development environments that allow you to easily write, run, and debug your code. They are fully integrated with your GitHub repository.</p>\n",
            "    <p><strong>Prerequisites:</strong></p>\n",
            "    <ul>\n",
            "      <li>Create your GitHub account.</li>\n",
            "    </ul>\n\n",
            "    <h2>Section 2: Git Development Cycle</h2>\n\n",
            "    <h3>0) Starting in Codespaces</h3>\n",
            "    <p><strong>When you open a Codespace, you&rsquo;re already inside the repository</strong> &mdash; no need to clone. A terminal and editor (like VS Code) are already set up for you.</p>\n\n",
            "    <h3>1) Creating a new branch using git checkout</h3>\n",
            "    <p>This command creates a new branch and switches to it. Work on a separate branch so you do not affect <code>main</code> directly.</p>\n",
            "    <ol>\n",
            "      <li>Open the <strong>Terminal</strong> tab in Codespaces.</li>\n",
            "      <li>Run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git checkout -b hello-git-branch</pre>\n',
            "    <ol start=\"3\">\n",
            '      <li>The output should match the handout. Take a screenshot as <span class="hos-cmd">01_new_branch_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p04_fig2.png", "PDF page 4 &mdash; terminal after creating branch"),
            fig("p04_fig3.png", "PDF page 4 &mdash; branch checkout context"),
            "    </div>\n\n",
            "    <h3>2) Listing current branches</h3>\n",
            "    <p>A Git project can have more than one branch. List them with <span class=\"hos-cmd\">git branch</span>.</p>\n",
            "    <ol>\n",
            "      <li>In your terminal, run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git branch</pre>\n',
            '    <p class="hos-pdf-note">If you do not see any branches, ensure you have a git repository in your working directory and at least one commit.</p>\n',
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">02_listing_branches_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p05_fig4.png", "PDF page 5 &mdash; git branch listing (1)"),
            fig("p05_fig5.png", "PDF page 5 &mdash; git branch listing (2)"),
            fig("p05_fig6.png", "PDF page 5 &mdash; git branch listing (3)"),
            "    </div>\n\n",
            "    <h3>3) Adding Files</h3>\n",
            "    <ol>\n",
            '      <li>In the Explorer, right-click &rarr; <strong>New File</strong> &rarr; name it <span class="hos-cmd">hello.txt</span>.</li>\n',
            "      <li>Add this line inside the file:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">Hello World</pre>\n\n',
            "    <h3>4) Checking status with git status</h3>\n",
            "    <p>Shows the working tree and staging area.</p>\n",
            "    <ol>\n",
            "      <li>Run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git status</pre>\n',
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">03_git_status_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            fig("p06_fig7.png", "PDF page 6 &mdash; git status output"),
            "\n",
            "    <h3>5) Adding files using git add</h3>\n",
            "    <ol>\n",
            "      <li>Run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git add --all</pre>\n',
            "    <p><em>Note:</em> Windows users may not see output.</p>\n",
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">04_git_add_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p07_fig8.png", "PDF page 7 &mdash; git add (1)"),
            fig("p07_fig9.png", "PDF page 7 &mdash; git add (2)"),
            fig("p07_fig10.png", "PDF page 7 &mdash; git add (3)"),
            "    </div>\n\n",
            "    <h3>6) Commit files using git commit</h3>\n",
            "    <ol>\n",
            "      <li>Run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git commit -m "Learning"</pre>\n',
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">05_git_commit_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n\n",
            "    <h3>7) Pushing your branch to GitHub</h3>\n",
            "    <p>The PDF uses a force push example; use caution with <span class=\"hos-cmd\">-f</span> on shared branches.</p>\n",
            "    <ol>\n",
            "      <li>Run (per handout):</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git push -f origin hello-git-branch</pre>\n',
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">06_pushing_github_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p08_fig11.png", "PDF page 8 &mdash; git push (1)"),
            fig("p08_fig12.png", "PDF page 8 &mdash; git push (2)"),
            fig("p08_fig13.png", "PDF page 8 &mdash; git push (3)"),
            "    </div>\n\n",
            "    <h3>8) Creating a Pull Request (PR)</h3>\n",
            "    <ol>\n",
            "      <li>Open your GitHub repository in the browser.</li>\n",
            '      <li>Use <strong>Compare &amp; pull request</strong>, then <strong>Create Pull Request</strong>.</li>\n',
            "      <li>Optional reviewers (not required for this HOS).</li>\n",
            '      <li><strong>Merge Pull Request</strong> and confirm, then <strong>Delete branch</strong> when done.</li>\n',
            "    </ol>\n",
            fig("p09_fig14.png", "PDF page 9 &mdash; open PR from GitHub"),
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p10_fig15.png", "PDF page 10 &mdash; PR steps (1)"),
            fig("p10_fig16.png", "PDF page 10 &mdash; PR steps (2)"),
            fig("p10_fig17.png", "PDF page 10 &mdash; PR steps (3)"),
            fig("p10_fig18.png", "PDF page 10 &mdash; PR steps (4)"),
            "    </div>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p11_fig19.png", "PDF page 11 &mdash; merge / delete branch (1)"),
            fig("p11_fig20.png", "PDF page 11 &mdash; merge / delete branch (2)"),
            fig("p11_fig21.png", "PDF page 11 &mdash; merge / delete branch (3)"),
            "    </div>\n\n",
            "    <h3>9) Pulling changes into your main branch</h3>\n",
            "    <ol>\n",
            "      <li>Run:</li>\n",
            "    </ol>\n",
            '    <pre class="hos-pre-df">git checkout main\ngit pull</pre>\n',
            "    <ol start=\"3\">\n",
            '      <li>Take <span class="hos-cmd">07_pulling_changes_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p12_fig22.png", "PDF page 12 &mdash; git pull (1)"),
            fig("p12_fig23.png", "PDF page 12 &mdash; git pull (2)"),
            "    </div>\n\n",
            "    <h2>Section 3: Coding Tools in GitHub Codespaces</h2>\n\n",
            "    <h3>1) Debugging in Codespaces</h3>\n",
            "    <ol>\n",
            '      <li>Create <span class="hos-cmd">addNumbers.py</span> with the sample from the PDF.</li>\n',
            "      <li>Set a breakpoint, then <strong>Run &rarr; Start Debugging</strong>, choose the Python debugger, and step with F11/F10.</li>\n",
            '      <li>Reference: <a href="https://cityuseattle.github.io/docs/debugging" target="_blank" rel="noopener">CityU debugging guide</a> (video).</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p13_fig24.png", "PDF page 13 &mdash; debugging (1)"),
            fig("p13_fig25.png", "PDF page 13 &mdash; debugging (2)"),
            "    </div>\n\n",
            "    <h3>2) Git in GitHub Codespaces</h3>\n",
            "    <ol>\n",
            "      <li><strong>File &rarr; Preferences &rarr; Settings</strong></li>\n",
            '      <li>Search <strong>Git Enabled</strong> and ensure options are enabled.</li>\n',
            "      <li>Take <span class=\"hos-cmd\">08_git_enable_firstname_lastname.png</span>.</li>\n",
            "    </ol>\n",
            fig("p14_fig26.png", "PDF page 14 &mdash; Git enabled settings"),
            "\n",
            "    <h3>3) Error Analysis</h3>\n",
            "    <p>Create <span class=\"hos-cmd\">addNumbers_Error.py</span> with intentional mistakes, then use the <strong>Problems</strong> tab to locate syntax errors and fix indentation.</p>\n",
            fig("p15_fig27.png", "PDF page 15 &mdash; Problems tab / syntax errors"),
            "\n",
            "    <h3>4) Linting</h3>\n",
            "    <p>Install <strong>Pylint</strong>, create <span class=\"hos-cmd\">addNumbers_Linting.py</span> as in the PDF, save, and review warnings in <strong>Problems</strong>.</p>\n",
            "    <ol>\n",
            '      <li>Take <span class="hos-cmd">09_linting_problems_firstname_lastname.png</span>.</li>\n',
            "    </ol>\n",
            '    <div class="hos-pdf-fig-grid">\n',
            fig("p16_fig28.png", "PDF page 16 &mdash; linting (1)"),
            fig("p16_fig29.png", "PDF page 16 &mdash; linting (2)"),
            fig("p16_fig30.png", "PDF page 16 &mdash; linting (3)"),
            "    </div>\n\n",
            "    <h2>Section 4: Pushing Your Work to GitHub</h2>\n",
            "    <p>Follow GitHub Classroom instructions to add, commit, and push your work and screenshots to the remote repository.</p>\n",
            full_pdf_text_append("02"),
            "  </section>\n",
        ]
    )


def main() -> None:
    text = TARGET.read_text(encoding="utf-8")
    start = text.index("  <!-- Complete HOS02A handout")
    end = text.index('  <div class="why-section">')
    new = text[:start] + build_handout() + "  <!-- Why & Purpose -->\n" + text[end:]
    new = new.replace(
        "<strong>The objective:</strong> Sequence the &lt;strong&gt;seven steps&lt;/strong&gt; of the HOS02A Git cookbook:",
        "<strong>The objective:</strong> Sequence the <strong>seven steps</strong> of the HOS02A Git cookbook:",
    )
    new = new.replace(
        "<p style=\"margin-top:.65rem;font-size:.88rem;color:#8b949e;line-height:1.55;max-width:820px;\">Full cookbook text from the PDF is below, then the interactive sequence. CS445 Software Process Management &mdash; CityU STC.</p>",
        "<p style=\"margin-top:.65rem;font-size:.88rem;color:#8b949e;line-height:1.55;max-width:820px;\">Full cookbook text from the PDF is below, then the interactive sequence activity. Course: CS445 Software Process Management &mdash; School of Technology &amp; Computing (STC), City University of Seattle (CityU).</p>",
    )
    new = re.sub(
        r"\n    \.hos-pdf-verbatim-details \{[^}]+\}\n    \.hos-pdf-sum \{[^}]+\}\n    \.hos-pdf-full-raw \{[^}]+\}\n    \.hos-pdf-fig-h \{[^}]+\}\n    \.hos-pdf-fig-all-grid \{[^}]+\}\n",
        "\n",
        new,
        count=1,
    )
    new = new.replace(
        "    /* HOS01A full handout (verbatim structure from PDF) */",
        "    /* HOS02A full handout (curated structure from PDF, same styles as HOS01) */",
    )
    if ".hos-pdf-note" not in new:
        new = new.replace(
            ".hos-pdf-source p { margin: .45rem 0; }",
            ".hos-pdf-source p { margin: .45rem 0; }\n    .hos-pdf-source .hos-pdf-note { font-size: .82rem; color: #8b949e; margin: .35rem 0 .75rem; }",
        )
    new = inject_verbatim_styles(new)
    TARGET.write_text(new, encoding="utf-8")
    print("Updated", TARGET)


if __name__ == "__main__":
    main()
