"""
Shared: append full plain-text PDF extraction (step-by-step) to curated HOS handouts.

Extract files live in `_pdf_extracts/hos{NN}_full.txt` (generated by `generate_hos_02_10.py`
when PDFs are available). Optional `hos04b_full.txt` for the without-Docker HOS04 variant.
"""
from __future__ import annotations

import html
import pathlib

BASE = pathlib.Path(__file__).resolve().parent
EXTRACT_DIR = BASE / "_pdf_extracts"

# Injected before </style> when handout includes .hos-pdf-verbatim-details
VERBATIM_STYLE_SNIPPET = """
    /* HOS verbatim PDF extract (collapsible full text) */
    .hos-pdf-extract-h {
      font-size: .95rem;
      font-weight: 800;
      color: #58a6ff;
      margin: 1.75rem 0 .5rem;
      border-top: 1px solid #30363d;
      padding-top: 1.25rem;
    }
    .hos-pdf-verbatim-details { margin: 1rem 0; }
    .hos-pdf-sum { cursor: pointer; color: #58a6ff; font-weight: 700; font-size: .85rem; }
    .hos-pdf-full-raw {
      max-height: 70vh;
      overflow: auto;
      background: #0d1117;
      border: 1px solid #30363d;
      border-radius: 8px;
      padding: 1rem;
      font-size: .72rem;
      line-height: 1.45;
      color: #c9d1d9;
      white-space: pre-wrap;
      word-break: break-word;
    }
    @media print {
      .hos-pdf-extract-h { border-top-color: #ccc !important; color: #0d47a1 !important; }
      .hos-pdf-verbatim-details { display: block !important; }
      .hos-pdf-verbatim-details summary { list-style: none; }
      .hos-pdf-full-raw {
        max-height: none !important;
        overflow: visible !important;
        background: #f8f9fa !important;
        color: #000 !important;
        border: 1px solid #ccc !important;
      }
      .hos-pdf-sum { color: #0a3069 !important; }
    }
"""


def full_pdf_text_append(mid: str) -> str:
    """HTML fragment: heading + note + <details> with full extracted PDF text (all steps)."""
    primary = EXTRACT_DIR / f"hos{mid}_full.txt"
    parts: list[str] = [
        '    <h2 class="hos-pdf-extract-h">Complete PDF text (step-by-step reference)</h2>\n',
        '    <p class="hos-pdf-note">The sections above are curated for scanning and figures. '
        "Expand below for the <strong>full plain-text extraction</strong> from the official PDF "
        "&mdash; every numbered step and instruction as extracted (spacing may differ from print layout).</p>\n",
    ]
    if not primary.is_file():
        parts.append(
            f'    <p class="hos-pdf-note">Missing <span class="hos-cmd">{primary.name}</span> in '
            f'<span class="hos-cmd">_pdf_extracts/</span>. Add it from the PDF so step-by-step text appears here.</p>\n'
        )
        return "".join(parts)
    esc = html.escape(primary.read_text(encoding="utf-8"))
    parts.extend(
        [
            '    <details class="hos-pdf-verbatim-details">\n',
            '      <summary class="hos-pdf-sum">Complete document text (extracted from PDF)</summary>\n',
            f'      <pre class="hos-pdf-full-raw">{esc}</pre>\n',
            "    </details>\n",
        ]
    )
    if mid == "04":
        alt = EXTRACT_DIR / "hos04b_full.txt"
        if alt.is_file():
            esc_alt = html.escape(alt.read_text(encoding="utf-8"))
            parts.extend(
                [
                    '    <details class="hos-pdf-verbatim-details">\n',
                    '      <summary class="hos-pdf-sum">Without Docker variant &mdash; complete document text (extracted)</summary>\n',
                    f'      <pre class="hos-pdf-full-raw">{esc_alt}</pre>\n',
                    "    </details>\n",
                ]
            )
        else:
            parts.append(
                '    <p class="hos-pdf-note">Non-Docker track: place plain-text export from '
                '<em>HOS04A - Databases - without Docker.pdf</em> in '
                '<span class="hos-cmd">_pdf_extracts/hos04b_full.txt</span> to show those steps here.</p>\n'
            )
    return "".join(parts)


def inject_verbatim_styles(page_html: str) -> str:
    """Ensure verbatim &lt;pre&gt; styles exist when details blocks are present."""
    if "hos-pdf-verbatim-details" not in page_html:
        return page_html
    if "/* HOS verbatim PDF extract (collapsible full text) */" in page_html:
        return page_html
    return page_html.replace("</style>", VERBATIM_STYLE_SNIPPET + "\n  </style>", 1)
