"""Per-industry content for Data Governance primer tab (O'Reilly-style pillars)."""

DATA = {
    "insurance": {
        "intro": "Regulators, rating bureaus, and reinsurers all demand traceable data. Governance balances state filing rules, actuarial models, and customer privacy.",
        "rows": [
            ("Ownership & stewardship", "Clear data owners for policy, claims, and actuarial datasets.", "Chief Underwriting Officer co-owns rating inputs; Chief Claims Officer owns FNOL quality metrics."),
            ("Policy & standards", "Written rules for acceptable sources, retention, and model use.", "NAIC model laws; internal policy on telematics and credit-based scoring where allowed."),
            ("Metadata & catalog", "Business definitions for premium, loss, exposure — aligned across PAS and data warehouse.", "ACORD-aligned glossary; lineage from ISO feeds to pricing engines."),
            ("Data quality", "Controls on completeness and timeliness for underwriting and claims.", "MVR freshness rules; FNOL field validation; cat model input reconciliation."),
            ("Privacy & compliance", "HIPAA where health lines; state privacy; fair lending analogs for scoring.", "Adverse action when credit affects pricing; breach playbooks per state DOI."),
            ("Lifecycle & lineage", "From quote to claim to reinsurance bordereaux with audit trail.", "Versioned rate filings; model change logs for RMS/AIR usage."),
        ],
        "cards": [
            ("Triangulation problem", "Agents, brokers, and direct channels create duplicate customer keys — governance must define golden record strategy."),
            ("Cat model governance", "Third-party cat models are black boxes; document assumptions whenever pricing or reinsurance depends on them."),
            ("Vendor access", "TPA and cloud PAS vendors hold production data — contracts must spell out subprocessors and breach notification."),
            ("Legacy cores", "Decades of policy admin on mainframes — metadata often incomplete; prioritize domains with regulatory exposure first."),
        ],
    },
    "fintech": {
        "intro": "Money movement data is heavily regulated. Governance aligns KYC/AML, market abuse surveillance, and open-banking APIs.",
        "rows": [
            ("Ownership & stewardship", "Business and technology owners for customer, transaction, and market data.", "CRO for risk aggregates; CCO for surveillance data; CTO for API platform logs."),
            ("Policy & standards", "Classification of sensitive data; approved vendors; retention tied to regs.", "PCI scope minimization; SOX controls for financial reporting feeds."),
            ("Metadata & catalog", "Security master, instrument identifiers, and legal entity resolution.", "LEI mapping; ISIN/CUSIP governance; golden security record."),
            ("Data quality", "Breaks in settlement or reference data can cascade — SLAs on feeds.", "Corporate actions processing; end-of-day reconciliation sign-off."),
            ("Privacy & compliance", "GDPR/CCPA; sector rules (FINRA, PCI DSS, PSD2).", "Consent for open banking; audit trail for best execution."),
            ("Lifecycle & lineage", "From order capture through clearing, settlement, and regulatory reporting.", "Trade lifecycle lineage for MiFID II / CAT-style obligations."),
        ],
        "cards": [
            ("Real-time vs batch", "Market data teams need different SLAs than regulatory reporting — split stewardship."),
            ("Vendor market data", "Bloomberg/Reuters licensing restricts redistribution — governance tracks entitlements."),
            ("Model risk", "Pricing and fraud models need inventory, validation, and change control."),
            ("Crypto overlap", "Where TradFi meets digital assets, wallet labeling and travel rule data need explicit policies."),
        ],
    },
    "ecommerce": {
        "intro": "Customer, catalog, and order data power conversion and fulfillment. Governance balances personalization with consent and marketplace fairness.",
        "rows": [
            ("Ownership & stewardship", "Owners for product catalog, customer PII, and seller data on marketplaces.", "Merchandising owns taxonomy; Trust & Safety owns seller fraud signals."),
            ("Policy & standards", "PII handling; review authenticity; ad/measurement data use.", "Cookie consent; first-party data strategy; MAP pricing policy data."),
            ("Metadata & catalog", "SKU, variant, and attribute definitions across web, OMS, and WMS.", "Global Item ID strategies; multilingual attribute governance."),
            ("Data quality", "Inventory accuracy; address validation; payment instrument integrity.", "ATS vs sellable stock; duplicate account detection."),
            ("Privacy & compliance", "GDPR/CCPA; COPPA where relevant; sector rules for payments.", "Data subject requests across CRM and CDP."),
            ("Lifecycle & lineage", "From clickstream to order to return — explainability for chargebacks.", "Attribution data lineage for marketing mix reporting."),
        ],
        "cards": [
            ("CDP sprawl", "Many tools claim to be the customer source of truth — pick one governed layer."),
            ("Seller data on marketplaces", "Boundary between marketplace operator and third-party seller obligations."),
            ("Search & ranking", "Features used in ranking may be regulated as unfair competition if opaque."),
            ("Returns fraud", "Governance links loss data to policy updates without exposing individual shoppers."),
        ],
    },
    "edtech": {
        "intro": "Student data is regulated (FERPA in the US) and ethically sensitive. Governance connects LMS, SIS, and AI tutors.",
        "rows": [
            ("Ownership & stewardship", "Registrar vs faculty vs vendor for roster and grades.", "Institutional Research owns official reporting; faculty own course content metadata."),
            ("Policy & standards", "Directory information rules; research use of learning analytics.", "IRB alignment for learning research; AI tutor logging policy."),
            ("Metadata & catalog", "Learning outcomes, competencies, and skills taxonomies.", "CEDS / IMS alignment for interoperability."),
            ("Data quality", "Roster sync; LMS–SIS integration health.", "Late add/drop propagation; xAPI statement quality."),
            ("Privacy & compliance", "FERPA; COPPA for K–12 vendors; international transfers.", "Parental consent workflows; data minimization for proctoring."),
            ("Lifecycle & lineage", "Retention of transcripts vs engagement telemetry.", "Deletion on withdrawal; research data de-identification."),
        ],
        "cards": [
            ("Vendor processors", "LMS and proctoring vendors — DPAs and subprocessors must be current."),
            ("Adaptive engines", "If placement decisions affect opportunity, document model oversight."),
            ("Credential wallets", "Verifiable credentials need issuer governance and revocation lists."),
            ("AI tutoring logs", "Prompt and response retention is an active policy frontier."),
        ],
    },
    "healthcare": {
        "intro": "Clinical and operational data are governed by HIPAA, 21 CFR Part 11 for many systems, and emerging AI rules. Patient safety depends on data integrity.",
        "rows": [
            ("Ownership & stewardship", "Clinical vs operational vs research ownership of patient records.", "CMIO for clinical documentation standards; HIM for release of information."),
            ("Policy & standards", "HIPAA minimum necessary; break-the-glass rules; device data provenance.", "EHR downtime procedures; amendment workflows."),
            ("Metadata & catalog", "Terminology — LOINC, SNOMED, RxNorm binding policies.", "Problem list governance; duplicate patient MPI management."),
            ("Data quality", "Identity resolution; lab result routing; imaging accession matching.", "Duplicate orders; wrong-patient error prevention metrics."),
            ("Privacy & compliance", "BA agreements; patient rights; state privacy overlays.", "Consent for secondary use; de-identification for research."),
            ("Lifecycle & lineage", "From device to EHR to claims — audit for recalls and surveillance.", "Implant registry linkage; post-market surveillance feeds."),
        ],
        "cards": [
            ("Interop mandates", "TEFCA / FHIR APIs increase exposure — scope access governance tightly."),
            ("AI/ML SaMD", "FDA expectations for locked models vs adaptive systems affect data capture."),
            ("Research vs care", "Single patient record used for both — firewalls for sponsored trials."),
            ("Cyber ransom", "Clinical data exfiltration drives incident playbooks beyond IT."),
        ],
    },
    "esports": {
        "intro": "Competitive integrity, broadcast rights, and player contracts all depend on authoritative match and viewership data.",
        "rows": [
            ("Ownership & stewardship", "League ops owns match results; teams own roster data; platforms own viewership.", "Publisher as ultimate authority on game patches affecting competition."),
            ("Policy & standards", "Anti-cheat telemetry; replay file integrity.", "Patch embargo windows; LAN tournament data capture standards."),
            ("Metadata & catalog", "Player IDs across games, regions, and name changes.", "Cross-game identity for esports org multi-roster."),
            ("Data quality", "Latency-corrected event ordering; observer sync.", "Disputed match reconstruction from server logs."),
            ("Privacy & compliance", "Minors on rosters; streaming GDPR; gambling integrations.", "Geoblocking data for betting partners."),
            ("Lifecycle & lineage", "From live server tick to VOD to analytics products.", "Rights chain for co-streaming and clip monetization."),
        ],
        "cards": [
            ("Third-party stats", "Riot vs HLTV vs community sites — canonical source disputes."),
            ("Betting feeds", "Sub-second latency governance when money depends on scores."),
            ("Talent visas", "Personal data shared with immigration — separate retention rules."),
            ("Sponsorship measurement", "Brand lift studies need clean exposure definitions."),
        ],
    },
    "video-game-retail": {
        "intro": "Retail and digital distribution data spans inventory, DRM entitlements, and player accounts — with regional regulatory variation.",
        "rows": [
            ("Ownership & stewardship", "Merchandising vs digital store vs physical supply chain datasets.", "Platform holder vs publisher data boundaries."),
            ("Policy & standards", "Age ratings metadata; regional SKU restrictions.", "Preorder bonus entitlement rules across channels."),
            ("Metadata & catalog", "Title IDs, editions, bundles across POS and digital.", "SKU rationalization when publishers re-master titles."),
            ("Data quality", "Inventory shrink; digital code redemption fraud.", "Street date enforcement telemetry."),
            ("Privacy & compliance", "COPPA for accounts; regional consumer laws.", "Loyalty program consent; email marketing preferences."),
            ("Lifecycle & lineage", "From wholesale purchase to sell-through to trade-in.", "Used-game refurbishment grading consistency."),
        ],
        "cards": [
            ("Channel conflict", "MAP and online pricing data shared selectively — leak risks."),
            ("Digital codes", "Bulk key generation and theft monitoring."),
            ("Pre-owned chain", "Customer device data wipe attestation."),
            ("Collectibles", "Authentication data for high-value SKUs."),
        ],
    },
    "ai-infrastructure": {
        "intro": "Training data, model weights, and experiment traces are core IP. Governance covers export control, safety evals, and reproducibility.",
        "rows": [
            ("Ownership & stewardship", "Research leads own datasets; platform eng owns cluster telemetry.", "Legal review for web-crawled corpora."),
            ("Policy & standards", "Data use agreements; license compatibility for fine-tunes.", "Open vs closed model release criteria."),
            ("Metadata & catalog", "Dataset cards; model cards; benchmark versioning.", "Prompt / completion logging policy for RLHF."),
            ("Data quality", "De-duplication; toxicity and PII filters; eval set hygiene.", "Contamination checks for benchmark leakage."),
            ("Privacy & compliance", "PII in training data; regional AI acts.", "Customer data in fine-tuning — contractual walls."),
            ("Lifecycle & lineage", "Checkpoint retention; experiment reproducibility from seed to cluster config.", "Artifact lineage for SOC2 audits."),
        ],
        "cards": [
            ("Multimodal assets", "Image/video rights differ from text — separate review tracks."),
            ("GPU job metadata", "Who ran what on shared clusters — chargeback and security."),
            ("Eval gaming", "Leaderboard integrity when teams optimize to public tests."),
            ("National security", "Export control lists for weights and training code."),
        ],
    },
    "restaurant": {
        "intro": "POS, delivery marketplaces, and loyalty systems fragment customer identity. Food safety adds traceability for supply chain data.",
        "rows": [
            ("Ownership & stewardship", "Franchisor vs franchisee data rights.", "Corporate menu vs local pricing experimentation."),
            ("Policy & standards", "Allergen information accuracy; tip pooling data.", "Third-party delivery fee pass-through transparency."),
            ("Metadata & catalog", "Menu item IDs across POS, apps, and kiosks.", "Recipe ingredient master for nutrition displays."),
            ("Data quality", "Inventory depletion; 86’d items synced to aggregators.", "Labor clock data for wage compliance."),
            ("Privacy & compliance", "Biometric time clocks; location in apps.", "Loyalty PII and payment tokenization."),
            ("Lifecycle & lineage", "From supplier lot to plate — recall readiness.", "Delivery handoff timestamps for dispute resolution."),
        ],
        "cards": [
            ("Aggregator menus", "Who fixes wrong items on DoorDash vs in-store POS?"),
            ("Franchise reporting", "Royalty calculations depend on governed sales data."),
            ("Ghost kitchens", "Brand data separation when multiple brands share a kitchen."),
            ("Waste analytics", "Food waste data sensitivity vs sustainability reporting."),
        ],
    },
    "sports": {
        "intro": "League stats, broadcast rights, and athlete biometric data converge — with collective bargaining shaping what can be collected.",
        "rows": [
            ("Ownership & stewardship", "League vs team vs player union data rights.", "Official stats provider as source of truth."),
            ("Policy & standards", "Wearable data in games; injury disclosure.", "Gambling integrity data sharing agreements."),
            ("Metadata & catalog", "Player IDs across leagues, trades, and international play.", "Venue and schedule master for logistics."),
            ("Data quality", "Official scoring corrections; clock synchronization.", "Tracking camera calibration for Next Gen stats."),
            ("Privacy & compliance", "Biometric laws; youth athlete protections.", "International transfer for global leagues."),
            ("Lifecycle & lineage", "From sensor to broadcast graphic to fantasy feed.", "Clip rights for social highlights."),
        ],
        "cards": [
            ("Fantasy & betting", "Latency and correction policies affect regulated markets."),
            ("NIL collegiate", "Amateurism data mixed with brand deal CRM — messy ownership."),
            ("Health data", "HIPAA rarely applies to teams — but CBAs still govern use."),
            ("Media rights", "Raw footage vs derived stats — different licensing."),
        ],
    },
    "maritime": {
        "intro": "SOLAS, customs, and charter-party disputes depend on authoritative voyage and cargo records.",
        "rows": [
            ("Ownership & stewardship", "Ship manager vs charterer vs port agent datasets.", "Flag state vs class society survey records."),
            ("Policy & standards", "Electronic logbooks; AIS data use.", "IMO data submission timeliness."),
            ("Metadata & catalog", "IMO numbers; voyage IDs; bill of lading linkage.", "Container slot vs cargo manifest alignment."),
            ("Data quality", "Draft and stability calculations feeding port clearance.", "ETA prediction inputs for berth scheduling."),
            ("Privacy & compliance", "Crew PII; sanctions screening lists.", "EU MRV and fuel reporting."),
            ("Lifecycle & lineage", "From stow plan to discharge survey — demurrage evidence.", "Chain of custody for reefer cargo."),
        ],
        "cards": [
            ("Paper persistence", "Scanned bills of lading still compete with eBL standards."),
            ("Charter disputes", "Data lineage for laytime calculations is litigation-ready."),
            ("Cyber on ships", "IT/OT segmentation governance for navigation systems."),
            ("Emissions", "CII data quality directly affects commercial viability."),
        ],
    },
    "telecom": {
        "intro": "Subscriber, usage, and network telemetry data are regulated and high-volume. Governance supports lawful intercept policy and spectrum reporting.",
        "rows": [
            ("Ownership & stewardship", "Network engineering vs marketing vs regulatory reporting owners.", "Roaming settlement data owned by wholesale teams."),
            ("Policy & standards", "Lawful intercept; CPNI in the US; emergency alerting data.", "Retention for billing disputes."),
            ("Metadata & catalog", "MSISDN/IMSI lifecycle; tower asset registry.", "Service catalog mapping SKU to network capabilities."),
            ("Data quality", "CDR completeness; drive-test calibration.", "Coverage map accuracy disclaimers."),
            ("Privacy & compliance", "Location precision; marketing opt-in; cross-border transfers.", "Net neutrality measurement methodology transparency."),
            ("Lifecycle & lineage", "Provisioning from order to network element activation.", "Number portability audit trails."),
        ],
        "cards": [
            ("5G slicing", "SLA data shared with enterprise customers — contractual precision."),
            ("Fraud systems", "Sensitive rules — governance restricts who can view tuning."),
            ("Tower leases", "Landlord data mixed with RF engineering — access control."),
            ("Open RAN", "Multi-vendor KPIs need normalized definitions."),
        ],
    },
    "logistics": {
        "intro": "Shipment status, inventory, and trade compliance data must be consistent across carriers, 3PLs, and customs.",
        "rows": [
            ("Ownership & stewardship", "Shipper vs carrier vs consignee responsibilities for data.", "4PL orchestration layers."),
            ("Policy & standards", "Dangerous goods declarations; denied party screening.", "EDI / API interchange standards with partners."),
            ("Metadata & catalog", "Tracking IDs; harmonized tariff codes; pack hierarchy.", "ASN vs receipt reconciliation keys."),
            ("Data quality", "Scan events; dwell time; exception codes.", "Dimensional weight vs actual — billing disputes."),
            ("Privacy & compliance", "Importer of record data; export controls.", "Driver hours (ELD) tamper-evidence."),
            ("Lifecycle & lineage", "From PO to POD — claims and insurance linkage.", "Cold chain temperature traceability."),
        ],
        "cards": [
            ("Visibility startups", "Many aggregators — identity resolution across SCAC codes."),
            ("Last mile", "Porch piracy data sensitivity vs marketing."),
            ("Returns flood", "Reverse logistics data quality affects inventory planning."),
            ("Customs", "Single window initiatives — master data alignment across borders."),
        ],
    },
    "video-platform": {
        "intro": "Rights, royalty, and recommendation data are commercially sensitive. Governance manages licensed content metadata and creator payouts.",
        "rows": [
            ("Ownership & stewardship", "Content ops vs personalization vs ads measurement owners.", "Music rights vs video asset hierarchies."),
            ("Policy & standards", "Copyright fingerprinting; regional availability; kids data.", "Creator monetization rule transparency data."),
            ("Metadata & catalog", "Title/episode/version graph; asset identifiers across CDN origins.", "Subtitle and dub track governance."),
            ("Data quality", "Playhead and completion metrics for royalty allocation.", "Ad impression reconciliation with third parties."),
            ("Privacy & compliance", "GDPR profiles; COPPA kids modes; biometric skip intro?", "Regional data residency for viewing history."),
            ("Lifecycle & lineage", "From ingest to encode ladder to client playback — DRM path.", "Take-down propagation across caches."),
        ],
        "cards": [
            ("Black box algorithms", "Regulators ask for explainability data — internal documentation burden."),
            ("Creator analytics", "What metrics are shared vs withheld competitively."),
            ("Live streaming", "Ephemeral content vs VOD archival policies."),
            ("Sports rights", "Geo-fence accuracy — contractual penalties."),
        ],
    },
    "oil": {
        "intro": "Reservoir, production, and emissions data underpin reserves reporting and HSE compliance — with SEC and climate disclosure scrutiny.",
        "rows": [
            ("Ownership & stewardship", "Petroleum engineering vs finance reserves booking.", "Joint venture data sharing across operators."),
            ("Policy & standards", "PRMS / SEC reserves definitions; methane monitoring standards.", "Wellhead data classification for trading."),
            ("Metadata & catalog", "Well IDs; seismic survey naming; pipeline asset registry.", "SCADA tag governance to corporate historians."),
            ("Data quality", "Metering allocation; flare measurement uncertainty.", "Production accounting close processes."),
            ("Privacy & compliance", "Landowner royalty statements; indigenous consultation records.", "Export and sanctions screening for crude buyers."),
            ("Lifecycle & lineage", "Exploration prospect to abandonment — document retention for liability.", "Spill response sensor data chain."),
        ],
        "cards": [
            ("Joint ventures", "Data sharing clauses in JOAs — operational vs reporting views."),
            ("Climate reporting", "Scope 1/2/3 data lineage must survive audit."),
            ("Trading arms", "Chinese walls between physical ops and paper trading data."),
            ("Legacy SCADA", "Air-gapped historians — metadata often tribal knowledge."),
        ],
    },
    "fishing": {
        "intro": "Catch reporting, quota, and chain-of-custody data underpin sustainability certifications and trade compliance.",
        "rows": [
            ("Ownership & stewardship", "Vessel captain vs processor vs retailer traceability.", "RFMO reporting obligations."),
            ("Policy & standards", "Electronic monitoring; discards reporting; IUU risk flags.", "MSC/ASC chain of custody paperwork."),
            ("Metadata & catalog", "Species codes; gear types; lot codes at landing.", "Transformation yields in processing plants."),
            ("Data quality", "Observer bias; mis-reporting incentives; weighbridge calibration.", "DNA spot-check sampling programs."),
            ("Privacy & compliance", "Crew lists; port state measures; import documentation.", "Sanctions on vessels and beneficial owners."),
            ("Lifecycle & lineage", "From catch area to consumer label — cold chain optional sensors.", "Mass-balance for mixed species loads."),
        ],
        "cards": [
            ("Developing fleet digitization", "Paper logbooks vs mobile apps — governance of hybrid regimes."),
            ("Fraud", "Species substitution — data governance meets forensic science."),
            ("Retail claims", "“Line-caught” marketing needs defensible lineage."),
            ("Climate", "Fuel and ice usage data for footprint claims."),
        ],
    },
    "manufacturing": {
        "intro": "MES, PLM, and ERP must agree on what is built, how, and with which revision — governance supports quality and recalls.",
        "rows": [
            ("Ownership & stewardship", "Engineering BOM vs manufacturing BOM vs service BOM owners.", "Plant quality vs central manufacturing ops."),
            ("Policy & standards", "ECO processes; calibration records; supplier PPAP data.", "Serial number issuance rules."),
            ("Metadata & catalog", "Part numbers; revision letters; alternates approval.", "Tooling and fixture IDs tied to work centers."),
            ("Data quality", "OEE inputs; scrap reason codes consistency.", "Inventory cycle count tolerance policies."),
            ("Privacy & compliance", "Worker safety data; ITAR/EAR for defense sub-tier.", "Environmental discharge monitoring."),
            ("Lifecycle & lineage", "From design release to serialized unit in field service.", "Recall scope queries by lot/date code."),
        ],
        "cards": [
            ("Brownfield plants", "PLC tag documentation debt — prioritize safety-critical tags."),
            ("Supplier portals", "Shared IP leakage risks in CAD drops."),
            ("Digital twin drift", "Simulation vs physical divergence governance."),
            ("Aftermarket", "Grey market parts — authenticity data schemes."),
        ],
    },
}
